spring.application.name=media-backlog

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/media_backlog
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
